# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: calendar

git:
  ignore_tags:
    - docs

release:
  header: |
    Download the release binary:

    ```sh
    # curl -fSL https://github.com/rakunlabs/calendar/releases/latest/download/calendar_Linux_x86_64.tar.gz | tar -xz --overwrite -C ~/bin/ calendar
    curl -fSL https://github.com/rakunlabs/calendar/releases/download/{{ .Tag }}/calendar_Linux_x86_64.tar.gz | tar -xz --overwrite -C ~/bin/ calendar
    ```
  footer: |
    **Full Changelog**: https://github.com/rakunlabs/calendar/compare/{{ .PreviousTag }}...{{ .Tag }}
before:
  hooks:
    - make ui-build
    - go mod tidy
builds:
  - id: calendar
    binary: calendar
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
    main: ./cmd/calendar
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    flags:
      - -trimpath
archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

dockers_v2:
  - id: calendar
    ids:
      - calendar
    dockerfile: ci/alpine.Dockerfile
    images:
      - ghcr.io/rakunlabs/calendar
    tags:
      - "{{ .Tag }}"
      - "{{ .Tag }}-alpine"
      - "{{ .Tag }}-alpine3.24.1"
      - "{{ if not .Prerelease }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - "--pull=true"
    labels:
      io.artifacthub.package.readme-url: https://raw.githubusercontent.com/rakunlabs/calendar/main/README.md
      io.artifacthub.package.maintainers: '[{"name":"Eray Ates","email":"eates23@gmail.com"}]'
      io.artifacthub.package.license: MIT
      org.opencontainers.image.description: calendar service
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.name: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "{{ .GitURL }}"
