// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "get": {
                "description": "GetEvents",
                "tags": [
                    "Events"
                ],
                "summary": "GetEvents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "description",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "event_group",
                        "name": "event_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "entity for relation",
                        "name": "entity",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "disabled",
                        "name": "disabled",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.Response-array_github_com_rakunlabs_calendar_pkg_models_Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            },
            "post": {
                "description": "AddEvents",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "AddEvents",
                "parameters": [
                    {
                        "description": "Event",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_rakunlabs_calendar_pkg_models.Event"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.Response-array_string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteEvents for multiple events",
                "tags": [
                    "Events"
                ],
                "summary": "DeleteEvents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/events/{id}": {
            "get": {
                "description": "GetEvent",
                "tags": [
                    "Events"
                ],
                "summary": "GetEvent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.Response-github_com_rakunlabs_calendar_pkg_models_Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            },
            "put": {
                "description": "PutEvent",
                "tags": [
                    "Events"
                ],
                "summary": "PutEvent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rakunlabs_calendar_pkg_models.Event"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteEvent",
                "tags": [
                    "Events"
                ],
                "summary": "DeleteEvent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/holidays": {
            "get": {
                "description": "Holidays for specific date",
                "tags": [
                    "Search"
                ],
                "summary": "Holidays",
                "parameters": [
                    {
                        "type": "string",
                        "description": "entity for relation",
                        "name": "entity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "country for relation",
                        "name": "event_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "date specific event",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.Response-array_github_com_rakunlabs_calendar_pkg_models_Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/ics": {
            "get": {
                "description": "GetICS",
                "tags": [
                    "iCal"
                ],
                "summary": "GetICS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "entity for relation",
                        "name": "entity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "country",
                        "name": "event_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "specific year events",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            },
            "post": {
                "description": "AddICS",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "iCal"
                ],
                "summary": "AddICS",
                "parameters": [
                    {
                        "type": "file",
                        "description": "ICS file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "event_group for ics",
                        "name": "event_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "timezone like Europe/Amsterdam default UTC",
                        "name": "tz",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/occurrences": {
            "get": {
                "tags": [
                    "Events"
                ],
                "summary": "Get event occurrences in a date range",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Inclusive start (RFC3339)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exclusive end (RFC3339), at most 400 days after from",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.Response-array_github_com_rakunlabs_calendar_pkg_models_Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/relations": {
            "get": {
                "description": "GetRelations",
                "tags": [
                    "Relations"
                ],
                "summary": "GetRelations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "entity",
                        "name": "entity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "event_id",
                        "name": "event_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "event_group",
                        "name": "event_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.Response-array_github_com_rakunlabs_calendar_pkg_models_Relation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            },
            "post": {
                "description": "AddRelations",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Relations"
                ],
                "summary": "AddRelations",
                "parameters": [
                    {
                        "description": "Relation",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_rakunlabs_calendar_pkg_models.Relation"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteRelations for multiple relations",
                "tags": [
                    "Relations"
                ],
                "summary": "DeleteRelations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "entity",
                        "name": "entity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "event_id",
                        "name": "event_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "event_group",
                        "name": "event_group",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.ResponseMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_rakunlabs_calendar_pkg_models.Event": {
            "type": "object",
            "properties": {
                "all_day": {
                    "type": "boolean"
                },
                "date_from": {
                    "type": "string"
                },
                "date_to": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "event_group": {
                    "$ref": "#/definitions/types.Null-string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rrule": {
                    "type": "string"
                },
                "tz": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "github_com_rakunlabs_calendar_pkg_models.Relation": {
            "type": "object",
            "properties": {
                "entity": {
                    "type": "string"
                },
                "event_group": {
                    "type": "string"
                },
                "event_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_handler.Message": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_handler.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total_item_count": {
                    "type": "integer"
                }
            }
        },
        "internal_adapter_handler.Response-array_github_com_rakunlabs_calendar_pkg_models_Event": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/internal_adapter_handler.Message"
                },
                "meta": {
                    "$ref": "#/definitions/internal_adapter_handler.Meta"
                },
                "payload": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rakunlabs_calendar_pkg_models.Event"
                    }
                }
            }
        },
        "internal_adapter_handler.Response-array_github_com_rakunlabs_calendar_pkg_models_Relation": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/internal_adapter_handler.Message"
                },
                "meta": {
                    "$ref": "#/definitions/internal_adapter_handler.Meta"
                },
                "payload": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rakunlabs_calendar_pkg_models.Relation"
                    }
                }
            }
        },
        "internal_adapter_handler.Response-array_string": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/internal_adapter_handler.Message"
                },
                "meta": {
                    "$ref": "#/definitions/internal_adapter_handler.Meta"
                },
                "payload": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_adapter_handler.Response-github_com_rakunlabs_calendar_pkg_models_Event": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/internal_adapter_handler.Message"
                },
                "meta": {
                    "$ref": "#/definitions/internal_adapter_handler.Meta"
                },
                "payload": {
                    "$ref": "#/definitions/github_com_rakunlabs_calendar_pkg_models.Event"
                }
            }
        },
        "internal_adapter_handler.ResponseMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/internal_adapter_handler.Message"
                }
            }
        },
        "types.Null-string": {
            "type": "object",
            "properties": {
                "v": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/calendar/v1",
	Schemes:          []string{},
	Title:            "calendar API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
